[book]
authors = ["piperTang"]
language = "en"
multilingual = false
src = "src"
title = "学无止境"


[output.html]
default-theme = "light"
preferred-dark-theme = "light"
git-repository-url = "https://github.com/piperTang/piperTang.github.io"
git-repository-icon = "fa-github"


[output.html.playground]
editable = true